### ISSUE TITLE
Request for the subdomain `leipzig.nix.ug`

### ISSUE THREAD

**Issue by transgirllucy** [nix-how/nix.ug#19]
Hello,

I hope this message finds you well. I am writing to request the subdomain "leipzig.nix.ug" for hosting a website and carrying out other projects.

I have been following the development of the nix.ug repository and I believe it would be a great opportunity to have a subdomain for the city of Leipzig. This would allow me to create a website that would showcase various projects and initiatives within the community.

I understand that the decision to grant a subdomain is ultimately up to the maintainers of the repository. However, I would like to offer my services in exchange for the subdomain. I am willing to contribute to the nix.ug project and help with any maintenance or development tasks as needed.

Thank you for your time and consideration. I look forward to hearing back from you.

**Comment by MatthewCroughan** [comment]
@mrtuxa not a problem, give me an IP address to point to and I'll do it. I was planning on automating this task, so it may very well be automated in the future for other people.

**Comment by transgirllucy** [comment]
as far i know should these ip's work


A-Record: 95.143.172.202
AAAA-Record: 2001:1a50:11:0:ec01:bfff:feef:205e
MX-Record:  antila.uberspace.de

**Comment by MatthewCroughan** [comment]
@mrtuxa The A and AAAA records have been set for leipzig.nix.ug, but I've left the MX record for now, since it could cause confusion as to who represents nix.ug, and I'm not sure how to handle that yet.

**Comment by mrtuxa** [comment]
please change the ip to

IPv4:  89.58.58.67
IPv6:   2a03:4000:6a:3cd::/64
