### ISSUE TITLE
Subdomain IP Change `leipzig.nix.ug`

### ISSUE THREAD

**Issue by transgirllucy** [nix-how/nix.ug#22]
please change the ip to

IPv4: 89.58.58.67
IPv6: 2a03:4000:6a:3cd::/64

**Comment by MatthewCroughan** [comment]
`2a03:4000:6a:3cd::/64` is not a valid ipv6 address, that is a range of IPs.  I have changed the IPv4 Address and removed the IPv6 Address for now until you give me a valid IPv6 address.

**Comment by transgirllucy** [comment]
> `2a03:4000:6a:3cd::/64` is not a valid ipv6 address, that is a range of IPs. I have changed the IPv4 Address and removed the IPv6 Address for now until you give me a valid IPv6 address.

could you please disable the cloudflare proxy (organge cloud)

**Comment by NobbZ** [comment]
I'm wondering if *.ug has HSTS by default… If that is the case, then the proxy wouldn't change anything.

And to be honest, I wouldn't stay on an HTTP site long, especially not when linked to it from an HTTPS one…

Can't you just set up HTTPS properly, then it will "just" work with cloudflare…

**Comment by MatthewCroughan** [comment]
@mrtuxa I won't remove the Cloudflare proxy, you should just set up letsencrypt certs or some other ACME automation correctly yourself. You should be hosting a HTTPS service. In the future we won't be using Cloudflare, and we will instead be using our own nameserver, so this will be more configurable in public.

**Comment by MatthewCroughan** [comment]
@mrtuxa looks like you fixed everything up, if you have an IPv6 address to give me then give me it as soon as you can, or I'm going to close this issue today
