### ISSUE TITLE
Hamburg User group - link broken

### ISSUE THREAD

**Issue by NobbZ** [nix-how/nix.ug#32]
The website for the Hamburg UG seems to be broken.

First its certificate is for the wrong subject.

If one continues anyway, one is redirect to a login page https://cloud.srx.dev/login

@sourceindex as they created the PR adding it.

@MatthewCroughan do you have any process about that? Perhaps additional contact information than just what is in the nix-file?

**Comment by MatthewCroughan** [comment]
I should add a maintainer field, yes.

**Comment by NobbZ** [comment]
Looking at @sourceindex GH profile, they seem to not be very active on GH, and creating the PR has been the only activity of them in the past year.

I think I will try to find other ways to reach out for them or finding contacts here…

**Comment by SebastianWendel** [comment]
Thank you for pointing this out. 

Unfortunately, the package for the website could not be built for some time and I have finally managed to fix the error.

From my point of view everything should be OK now. Can I still support in some way or can the issue be closed?
