### ISSUE TITLE
How to obtain mycity.nix.ug?

### ISSUE THREAD

**Issue by tfc** [nix-how/nix.ug#61]
Hi, i'm launching a new nix UG.
Who can i talk to to obtain a mycity.nix.ug address to point to the UG website?

**Comment by MatthewCroughan** [comment]
Me, though I want to automate it at some point. What is the DNS A record you want created?

**Comment by tfc** [comment]
Can you point `habrawo.nix.ug` to A `195.201.237.10`, AAAA `2a01:4f8:c013:4ef9::`? This would be great. :)

**Comment by MatthewCroughan** [comment]
@tfc Done

**Comment by tfc** [comment]
Thank you very much, Matthew!
